/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as HealthRouteImport } from './routes/health'
import { Route as V1ProfilesQueryRouteImport } from './routes/v1/profiles/query'
import { Route as V1WalletsAddressRouteImport } from './routes/v1/wallets/$address'
import { Route as V1WalletsImportRouteImport } from './routes/v1/wallets/import'
import { Route as V1WalletsAddressActivityRouteImport } from './routes/v1/wallets/$address/activity'
import { Route as V1WalletsAddressControlsRouteImport } from './routes/v1/wallets/$address/controls'
import { Route as V1WalletsAddressEarningsRouteImport } from './routes/v1/wallets/$address/earnings'
import { Route as V1WalletsAddressProfileRouteImport } from './routes/v1/wallets/$address/profile'
import { Route as V1WalletsAddressWithdrawRouteImport } from './routes/v1/wallets/$address/withdraw'
import { Route as V1WalletsAddressEarningsHistoryRouteImport } from './routes/v1/wallets/$address/earnings/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProfilesQueryRoute = V1ProfilesQueryRouteImport.update({
  id: '/v1/profiles/query',
  path: '/v1/profiles/query',
  getParentRoute: () => rootRouteImport,
} as any)
const V1WalletsAddressRoute = V1WalletsAddressRouteImport.update({
  id: '/v1/wallets/$address',
  path: '/v1/wallets/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const V1WalletsImportRoute = V1WalletsImportRouteImport.update({
  id: '/v1/wallets/import',
  path: '/v1/wallets/import',
  getParentRoute: () => rootRouteImport,
} as any)
const V1WalletsAddressActivityRoute =
  V1WalletsAddressActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => V1WalletsAddressRoute,
  } as any)
const V1WalletsAddressControlsRoute =
  V1WalletsAddressControlsRouteImport.update({
    id: '/controls',
    path: '/controls',
    getParentRoute: () => V1WalletsAddressRoute,
  } as any)
const V1WalletsAddressEarningsRoute =
  V1WalletsAddressEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => V1WalletsAddressRoute,
  } as any)
const V1WalletsAddressProfileRoute = V1WalletsAddressProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => V1WalletsAddressRoute,
} as any)
const V1WalletsAddressWithdrawRoute =
  V1WalletsAddressWithdrawRouteImport.update({
    id: '/withdraw',
    path: '/withdraw',
    getParentRoute: () => V1WalletsAddressRoute,
  } as any)
const V1WalletsAddressEarningsHistoryRoute =
  V1WalletsAddressEarningsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => V1WalletsAddressEarningsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/v1/profiles/query': typeof V1ProfilesQueryRoute
  '/v1/wallets/$address': typeof V1WalletsAddressRouteWithChildren
  '/v1/wallets/import': typeof V1WalletsImportRoute
  '/v1/wallets/$address/activity': typeof V1WalletsAddressActivityRoute
  '/v1/wallets/$address/controls': typeof V1WalletsAddressControlsRoute
  '/v1/wallets/$address/earnings': typeof V1WalletsAddressEarningsRouteWithChildren
  '/v1/wallets/$address/profile': typeof V1WalletsAddressProfileRoute
  '/v1/wallets/$address/withdraw': typeof V1WalletsAddressWithdrawRoute
  '/v1/wallets/$address/earnings/history': typeof V1WalletsAddressEarningsHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/v1/profiles/query': typeof V1ProfilesQueryRoute
  '/v1/wallets/$address': typeof V1WalletsAddressRouteWithChildren
  '/v1/wallets/import': typeof V1WalletsImportRoute
  '/v1/wallets/$address/activity': typeof V1WalletsAddressActivityRoute
  '/v1/wallets/$address/controls': typeof V1WalletsAddressControlsRoute
  '/v1/wallets/$address/earnings': typeof V1WalletsAddressEarningsRouteWithChildren
  '/v1/wallets/$address/profile': typeof V1WalletsAddressProfileRoute
  '/v1/wallets/$address/withdraw': typeof V1WalletsAddressWithdrawRoute
  '/v1/wallets/$address/earnings/history': typeof V1WalletsAddressEarningsHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/v1/profiles/query': typeof V1ProfilesQueryRoute
  '/v1/wallets/$address': typeof V1WalletsAddressRouteWithChildren
  '/v1/wallets/import': typeof V1WalletsImportRoute
  '/v1/wallets/$address/activity': typeof V1WalletsAddressActivityRoute
  '/v1/wallets/$address/controls': typeof V1WalletsAddressControlsRoute
  '/v1/wallets/$address/earnings': typeof V1WalletsAddressEarningsRouteWithChildren
  '/v1/wallets/$address/profile': typeof V1WalletsAddressProfileRoute
  '/v1/wallets/$address/withdraw': typeof V1WalletsAddressWithdrawRoute
  '/v1/wallets/$address/earnings/history': typeof V1WalletsAddressEarningsHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/health'
    | '/v1/profiles/query'
    | '/v1/wallets/$address'
    | '/v1/wallets/import'
    | '/v1/wallets/$address/activity'
    | '/v1/wallets/$address/controls'
    | '/v1/wallets/$address/earnings'
    | '/v1/wallets/$address/profile'
    | '/v1/wallets/$address/withdraw'
    | '/v1/wallets/$address/earnings/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/health'
    | '/v1/profiles/query'
    | '/v1/wallets/$address'
    | '/v1/wallets/import'
    | '/v1/wallets/$address/activity'
    | '/v1/wallets/$address/controls'
    | '/v1/wallets/$address/earnings'
    | '/v1/wallets/$address/profile'
    | '/v1/wallets/$address/withdraw'
    | '/v1/wallets/$address/earnings/history'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/health'
    | '/v1/profiles/query'
    | '/v1/wallets/$address'
    | '/v1/wallets/import'
    | '/v1/wallets/$address/activity'
    | '/v1/wallets/$address/controls'
    | '/v1/wallets/$address/earnings'
    | '/v1/wallets/$address/profile'
    | '/v1/wallets/$address/withdraw'
    | '/v1/wallets/$address/earnings/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  HealthRoute: typeof HealthRoute
  V1ProfilesQueryRoute: typeof V1ProfilesQueryRoute
  V1WalletsAddressRoute: typeof V1WalletsAddressRouteWithChildren
  V1WalletsImportRoute: typeof V1WalletsImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/profiles/query': {
      id: '/v1/profiles/query'
      path: '/v1/profiles/query'
      fullPath: '/v1/profiles/query'
      preLoaderRoute: typeof V1ProfilesQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/wallets/$address': {
      id: '/v1/wallets/$address'
      path: '/v1/wallets/$address'
      fullPath: '/v1/wallets/$address'
      preLoaderRoute: typeof V1WalletsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/wallets/import': {
      id: '/v1/wallets/import'
      path: '/v1/wallets/import'
      fullPath: '/v1/wallets/import'
      preLoaderRoute: typeof V1WalletsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/wallets/$address/activity': {
      id: '/v1/wallets/$address/activity'
      path: '/activity'
      fullPath: '/v1/wallets/$address/activity'
      preLoaderRoute: typeof V1WalletsAddressActivityRouteImport
      parentRoute: typeof V1WalletsAddressRoute
    }
    '/v1/wallets/$address/controls': {
      id: '/v1/wallets/$address/controls'
      path: '/controls'
      fullPath: '/v1/wallets/$address/controls'
      preLoaderRoute: typeof V1WalletsAddressControlsRouteImport
      parentRoute: typeof V1WalletsAddressRoute
    }
    '/v1/wallets/$address/earnings': {
      id: '/v1/wallets/$address/earnings'
      path: '/earnings'
      fullPath: '/v1/wallets/$address/earnings'
      preLoaderRoute: typeof V1WalletsAddressEarningsRouteImport
      parentRoute: typeof V1WalletsAddressRoute
    }
    '/v1/wallets/$address/profile': {
      id: '/v1/wallets/$address/profile'
      path: '/profile'
      fullPath: '/v1/wallets/$address/profile'
      preLoaderRoute: typeof V1WalletsAddressProfileRouteImport
      parentRoute: typeof V1WalletsAddressRoute
    }
    '/v1/wallets/$address/withdraw': {
      id: '/v1/wallets/$address/withdraw'
      path: '/withdraw'
      fullPath: '/v1/wallets/$address/withdraw'
      preLoaderRoute: typeof V1WalletsAddressWithdrawRouteImport
      parentRoute: typeof V1WalletsAddressRoute
    }
    '/v1/wallets/$address/earnings/history': {
      id: '/v1/wallets/$address/earnings/history'
      path: '/history'
      fullPath: '/v1/wallets/$address/earnings/history'
      preLoaderRoute: typeof V1WalletsAddressEarningsHistoryRouteImport
      parentRoute: typeof V1WalletsAddressEarningsRoute
    }
  }
}

interface V1WalletsAddressEarningsRouteChildren {
  V1WalletsAddressEarningsHistoryRoute: typeof V1WalletsAddressEarningsHistoryRoute
}

const V1WalletsAddressEarningsRouteChildren: V1WalletsAddressEarningsRouteChildren =
  {
    V1WalletsAddressEarningsHistoryRoute: V1WalletsAddressEarningsHistoryRoute,
  }

const V1WalletsAddressEarningsRouteWithChildren =
  V1WalletsAddressEarningsRoute._addFileChildren(
    V1WalletsAddressEarningsRouteChildren,
  )

interface V1WalletsAddressRouteChildren {
  V1WalletsAddressActivityRoute: typeof V1WalletsAddressActivityRoute
  V1WalletsAddressControlsRoute: typeof V1WalletsAddressControlsRoute
  V1WalletsAddressEarningsRoute: typeof V1WalletsAddressEarningsRouteWithChildren
  V1WalletsAddressProfileRoute: typeof V1WalletsAddressProfileRoute
  V1WalletsAddressWithdrawRoute: typeof V1WalletsAddressWithdrawRoute
}

const V1WalletsAddressRouteChildren: V1WalletsAddressRouteChildren = {
  V1WalletsAddressActivityRoute: V1WalletsAddressActivityRoute,
  V1WalletsAddressControlsRoute: V1WalletsAddressControlsRoute,
  V1WalletsAddressEarningsRoute: V1WalletsAddressEarningsRouteWithChildren,
  V1WalletsAddressProfileRoute: V1WalletsAddressProfileRoute,
  V1WalletsAddressWithdrawRoute: V1WalletsAddressWithdrawRoute,
}

const V1WalletsAddressRouteWithChildren =
  V1WalletsAddressRoute._addFileChildren(V1WalletsAddressRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  HealthRoute: HealthRoute,
  V1ProfilesQueryRoute: V1ProfilesQueryRoute,
  V1WalletsAddressRoute: V1WalletsAddressRouteWithChildren,
  V1WalletsImportRoute: V1WalletsImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
