
import * as THREE from 'three'
import{EffectComposer}from 'three/examples/jsm/postprocessing/EffectComposer.js'
import{RenderPass}from 'three/examples/jsm/postprocessing/RenderPass.js'
import{UnrealBloomPass}from 'three/examples/jsm/postprocessing/UnrealBloomPass.js'
import{ShaderPass}from 'three/examples/jsm/postprocessing/ShaderPass.js'
import{GLTFLoader}from 'three/examples/jsm/loaders/GLTFLoader.js'

export function initLandingScene(){
const GLB_URL='/model.glb',TARGET_H=1.80,LAYERS={NONE:0,TORUS_SCENE:1,BLOOM_SCENE:2,ENTIRE_SCENE:3}
const nearColor='#110923',farColor='#271350',rimColor='#3e1a7f',fillColor='#5820b1'
const bgTop='#9860de',bgBottom='#b990e4',bgGlow='#d6beed'
function hexToVec3(hex){const h=hex.replace('#','');return new THREE.Vector3(parseInt(h.substring(0,2),16)/255,parseInt(h.substring(2,4),16)/255,parseInt(h.substring(4,6),16)/255)}
const canvas=document.getElementById('scene');if(!(canvas instanceof HTMLCanvasElement))return()=>{}
const poster=document.getElementById('scenePoster')
const dpr=Math.min(window.devicePixelRatio||1,2)
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(dpr);renderer.setSize(window.innerWidth,window.innerHeight);renderer.setClearColor(0x000000,1)
const scene=new THREE.Scene();scene.background=new THREE.Color(0x000000)
const camera=new THREE.PerspectiveCamera(36,window.innerWidth/window.innerHeight,0.1,100);camera.position.set(0,0,1.96);camera.layers.enableAll();scene.add(camera)
const group=new THREE.Group();scene.add(group)
const uniforms={iResolution:{value:new THREE.Vector2(window.innerWidth*dpr,window.innerHeight*dpr)},uAspect:{value:window.innerWidth/window.innerHeight},iTime:{value:0},iAlpha:{value:0},iClickT:{value:-10},uCamDist:{value:1.96},uNear:{value:hexToVec3(nearColor)},uFar:{value:hexToVec3(farColor)},uRim:{value:hexToVec3(rimColor)},uFill:{value:hexToVec3(fillColor)},uFreq:{value:65},uLineW:{value:2.85},uLineGain:{value:1.92},uWarmPow:{value:1.7},uFillGain:{value:0.225},uRimPow:{value:4.2},uRimGain:{value:2.44},uPulseSpeed:{value:1.85},uPulseWidth:{value:13.2},uPulseGain:{value:0.62}}
const material=new THREE.ShaderMaterial({uniforms,vertexShader:`varying vec3 vViewPos;varying vec3 vNormalView;void main(){vec4 mv=modelViewMatrix*vec4(position,1.0);vViewPos=mv.xyz;vNormalView=normalMatrix*normal;gl_Position=projectionMatrix*mv;}`,fragmentShader:`precision highp float;varying vec3 vViewPos;varying vec3 vNormalView;uniform vec2 iResolution;uniform float uAspect,iTime,iAlpha,iClickT,uCamDist;uniform vec3 uNear,uFar,uRim,uFill;uniform float uFreq,uLineW,uLineGain,uWarmPow,uFillGain,uRimPow,uRimGain,uPulseSpeed,uPulseWidth,uPulseGain;void main(){vec3 n=normalize(vNormalView);if(!gl_FrontFacing)n=-n;vec3 vd=normalize(-vViewPos);float facing=clamp(dot(n,vd),0.0,1.0);float depth=length(vViewPos);float band=depth*uFreq;float fr=fract(band);float dist=min(fr,1.0-fr);float aa=max(fwidth(band),1e-4);float line=1.0-smoothstep(0.0,aa*uLineW,dist);line*=1.0-smoothstep(0.32,0.80,aa);float warm=pow(facing,uWarmPow);vec3 lineCol=mix(uFar,uNear,warm);float rim=pow(1.0-facing,uRimPow);float age=iTime-iClickT;float pulse=0.0;if(age>0.0&&age<3.0){float front=(uCamDist-1.0)+age*uPulseSpeed;pulse=exp(-pow((depth-front)*uPulseWidth,2.0))*exp(-age*1.1);}vec3 col=lineCol*line*uLineGain;col+=uFill*facing*uFillGain;col+=uRim*rim*uRimGain;col+=lineCol*line*pulse*uPulseGain;col*=mix(1.0,0.74,clamp((depth-(uCamDist-0.9))/2.0,0.0,1.0));col=max(col,0.0)*iAlpha;gl_FragColor=vec4(col,1.0);}`,side:THREE.DoubleSide,extensions:{derivatives:true}})
let disposed=false
new GLTFLoader().load(GLB_URL,(gltf)=>{if(disposed)return;let src=null;gltf.scene.traverse(o=>{if(o.isMesh&&!src)src=o});if(!src)return;const geo=src.geometry;geo.computeBoundingBox();const bb=geo.boundingBox;const c=new THREE.Vector3();bb.getCenter(c);const sz=new THREE.Vector3();bb.getSize(sz);geo.translate(-c.x,-c.y,-c.z);if(!geo.attributes.normal)geo.computeVertexNormals();const s=TARGET_H/sz.y;const mesh=new THREE.Mesh(geo,material);mesh.scale.setScalar(s);mesh.layers.set(LAYERS.ENTIRE_SCENE);mesh.layers.enable(LAYERS.BLOOM_SCENE);group.add(mesh);meshInAt=performance.now()/1000})
const bgUniforms={iTime:{value:0},uAspect:{value:window.innerWidth/window.innerHeight},iAlpha:{value:0},uBgTop:{value:hexToVec3(bgTop)},uBgBottom:{value:hexToVec3(bgBottom)},uBgGlow:{value:hexToVec3(bgGlow)},uGlowAmount:{value:0.41},uBgFlow:{value:0.3}}
const bgMesh=new THREE.Mesh(new THREE.PlaneGeometry(2,2),new THREE.ShaderMaterial({uniforms:bgUniforms,vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,1.0);}`,fragmentShader:`precision highp float;varying vec2 vUv;uniform float iTime,uAspect,iAlpha;uniform vec3 uBgTop,uBgBottom,uBgGlow;uniform float uGlowAmount,uBgFlow;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float vnoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);float a=hash(i),b=hash(i+vec2(1,0)),c=hash(i+vec2(0,1)),d=hash(i+vec2(1,1));return mix(mix(a,b,f.x),mix(c,d,f.x),f.y);}float fbm(vec2 p){float s=0.0,a=0.5;for(int i=0;i<4;i++){s+=a*vnoise(p);p*=2.02;a*=0.5;}return s;}void main(){vec2 uv=vUv;vec3 col=mix(uBgBottom,uBgTop,clamp(uv.y,0.0,1.0));vec2 c=uv-vec2(0.5,0.52);c.x*=uAspect;float r=length(c);float glow=exp(-r*r*4.5)*uGlowAmount*(0.82+0.18*sin(iTime*0.4));col+=uBgGlow*glow;float n=fbm(uv*vec2(2.2,3.0)+vec2(iTime*0.02,iTime*0.014));col+=uBgGlow*0.10*uBgFlow*n*smoothstep(1.05,0.25,r);col*=1.0-0.55*smoothstep(0.45,1.15,r);gl_FragColor=vec4(col*iAlpha,1.0);}`,depthTest:false,depthWrite:false}));bgMesh.frustumCulled=false;bgMesh.renderOrder=-10;bgMesh.layers.set(LAYERS.ENTIRE_SCENE);scene.add(bgMesh)
const n=340,pos=new Float32Array(n*3),seed=new Float32Array(n),sz2=new Float32Array(n),warmA=new Float32Array(n)
for(let i=0;i<n;i++){pos[i*3]=(Math.random()*2-1)*1.6;pos[i*3+1]=(Math.random()*2-1)*1.35;pos[i*3+2]=(Math.random()*2-1)*1.6;seed[i]=Math.random();sz2[i]=0.5+Math.random()*Math.random()*2.4;warmA[i]=Math.random()<0.28?Math.random():0.0}
const pGeo=new THREE.BufferGeometry();pGeo.setAttribute('position',new THREE.BufferAttribute(pos,3));pGeo.setAttribute('aSeed',new THREE.BufferAttribute(seed,1));pGeo.setAttribute('aSize',new THREE.BufferAttribute(sz2,1));pGeo.setAttribute('aWarm',new THREE.BufferAttribute(warmA,1))
const pUniforms={iTime:{value:0},uSize:{value:5},uDrift:{value:1.16},uDpr:{value:dpr},uWarm:{value:hexToVec3(nearColor)},uCool:{value:hexToVec3(farColor)},uGlow:{value:1.32},iAlpha:{value:0}}
const points=new THREE.Points(pGeo,new THREE.ShaderMaterial({uniforms:pUniforms,vertexShader:`attribute float aSeed,aSize,aWarm;uniform float iTime,uSize,uDrift,uDpr;varying float vWarm,vTw;void main(){vec3 p=position;p+=uDrift*vec3(0.10*sin(iTime*0.25+aSeed*6.2831),0.08*sin(iTime*0.20+aSeed*3.7)+0.05*sin(iTime*0.11+aSeed*2.0),0.10*cos(iTime*0.23+aSeed*4.1));vec4 mv=modelViewMatrix*vec4(p,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=max(aSize*uSize*uDpr/max(-mv.z,0.1),2.0*uDpr);vWarm=aWarm;vTw=0.5+0.5*sin(iTime*(0.7+aSeed*1.6)+aSeed*6.2831);}`,fragmentShader:`precision highp float;varying float vWarm,vTw;uniform vec3 uWarm,uCool;uniform float uGlow,iAlpha;void main(){vec2 d=gl_PointCoord-0.5;float r=length(d);float a=smoothstep(0.5,0.0,r);a*=a;vec3 c=mix(uCool,uWarm,vWarm);gl_FragColor=vec4(c*uGlow*(0.7+0.3*vTw)*a*iAlpha,a);}`,transparent:true,blending:THREE.AdditiveBlending,depthTest:true,depthWrite:false}));points.frustumCulled=false;points.layers.set(LAYERS.ENTIRE_SCENE);scene.add(points)
const FP={uniforms:{tDiffuse:{value:null},uExposure:{value:0.96},uVignette:{value:0.66},uGrain:{value:0.106},uFloor:{value:0.04},uAspect:{value:window.innerWidth/window.innerHeight},uTime:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,1.0);}`,fragmentShader:`precision highp float;uniform sampler2D tDiffuse;uniform float uExposure,uVignette,uGrain,uFloor,uAspect,uTime;varying vec2 vUv;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec3 c=texture2D(tDiffuse,vUv).rgb;vec2 vg=vUv-0.5;vg.x*=uAspect;c*=1.0-uVignette*dot(vg,vg)*2.2;c=1.0-exp(-c*uExposure);c=max(c-uFloor,0.0);c+=(hash(gl_FragCoord.xy)-0.5)/255.0;c+=(hash(vUv*vec2(1917.0,1083.0)+fract(uTime)*97.0)-0.5)*uGrain;gl_FragColor=vec4(c,1.0);}`}
const composer=new EffectComposer(renderer,new THREE.WebGLRenderTarget(window.innerWidth,window.innerHeight,{type:THREE.HalfFloatType,samples:4}));composer.addPass(new RenderPass(scene,camera));const bloomPass=new UnrealBloomPass(new THREE.Vector2(window.innerWidth,window.innerHeight),0.88,0.66,0.6);composer.addPass(bloomPass);const tonePass=new ShaderPass(FP);composer.addPass(tonePass)
function onPointerDown(){uniforms.iClickT.value=performance.now()/1000}
canvas.addEventListener('pointerdown',onPointerDown,{passive:true})
function onResize(){const w=window.innerWidth,h=window.innerHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();composer.setSize(w,h);bloomPass.setSize(w,h);tonePass.uniforms.uAspect.value=w/h;uniforms.iResolution.value.set(w*dpr,h*dpr);uniforms.uAspect.value=w/h;bgUniforms.uAspect.value=w/h}
window.addEventListener('resize',onResize);onResize()
let yaw=0,startTime=performance.now()/1000,prevNow=startTime,meshInAt=Infinity,animationFrame=0
function onVisibilityChange(){if(!document.hidden)prevNow=performance.now()/1000}
document.addEventListener('visibilitychange',onVisibilityChange,{passive:true})
function animate(){if(disposed)return;animationFrame=requestAnimationFrame(animate);const now=performance.now()/1000;const dt=Math.min(now-prevNow,0.1);prevNow=now;const time=now-startTime;uniforms.iTime.value=now;bgUniforms.iTime.value=now;pUniforms.iTime.value=now;yaw+=-0.15*dt;uniforms.uCamDist.value=1.96;const cy=Math.cos(yaw),sy=Math.sin(yaw);camera.position.set(sy*1.96,0.42,cy*1.96);camera.lookAt(0,0.42,0);const b=1.0+0.38*0.006*Math.sin(time*1.1);group.scale.setScalar(b);bgUniforms.iAlpha.value=1;pUniforms.iAlpha.value=1;const mf=Math.min(Math.max(now-meshInAt,0)/0.12,1.0);uniforms.iAlpha.value=mf*mf*(3.0-2.0*mf);tonePass.uniforms.uTime.value=now;composer.render();if(meshInAt!==Infinity&&mf>=1)poster?.classList.add('ready')}
animate()
return()=>{disposed=true;cancelAnimationFrame(animationFrame);window.removeEventListener('resize',onResize);document.removeEventListener('visibilitychange',onVisibilityChange);canvas.removeEventListener('pointerdown',onPointerDown);renderer.dispose();composer.dispose()}
}
